### PR TITLE
Make shard compatible with Crystal 1.0

### PR DESCRIPTION
**Pull request by n-rodriguez**

### CODE REVIEW

**Review by straight-shoota — APPROVED** [review]

**Comment by n-rodriguez** [comment]
hi there! any news?

**Comment by beta-ziliani** [comment]
Is there a reason to drop compatibility with 0.35.1? why not make it >=0.35.1?

**Comment by n-rodriguez** [comment]
@beta-ziliani :+1:  fixed!

**Review by beta-ziliani — APPROVED** [review]

**Review by oprypin — APPROVED** [review]

**Comment by n-rodriguez** [comment]
@straight-shoota thank you!

**Pull request merged**
